name = "ElectronicStructurePySCF"
uuid = "14ae0224-3a94-4a0c-83bc-25b293227ef3"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
ElectronicStructure = "f7ec468b-4310-4c77-90aa-f73697106762"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
ElectronicStructure = ">= 0.1.3"
PyCall = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
